services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backup_automation
    environment:
      - FTP_HOST=${FTP_HOST}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TIME_ZONE=${TIME_ZONE}
      - LOCAL_BACKUP_PATH=${LOCAL_BACKUP_PATH}
    volumes:
      - /root:/usr/src/app/data
      - /var/log/backup_automation:/usr/src/app/logs
    restart: always
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /root/backups:/srv #Change to match your directory
      - /root/automation-server-backup/filebrowser-config/database.db:/database.db
      - /root/automation-server-backup/filebrowser-config/settings.json:/etc/filebrowser/settings.json
      - /root/automation-server-backup/filebrowser-config/branding:/branding
    command: [
      "--database", "/database.db",
      "--config", "/etc/filebrowser/settings.json",
    ]
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 8095:80 #Change the port if needed